--
-- PostgreSQL database dump
--

-- Dumped from database version 12.18
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-08 17:59:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 16579)
-- Name: colaborador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.colaborador (
    id integer NOT NULL,
    apellido character varying(255),
    cargo character varying(255),
    documento_identificacion integer,
    especialidad character varying(255),
    nombre character varying(255),
    tipo_documento character varying(3)
);


ALTER TABLE public.colaborador OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16577)
-- Name: colaborador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.colaborador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.colaborador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16652)
-- Name: detalle_historia_clinica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_historia_clinica (
    id integer NOT NULL,
    alimentacion character varying(255),
    fecha_hora timestamp(6) without time zone,
    frecuencia_cardiaca numeric(38,2),
    frecuencia_respiratoria numeric(38,2),
    habitad character varying(255),
    observacion character varying(255),
    peso numeric(38,2),
    temperatura character varying(255),
    colaborador_id integer,
    historia_clinica_id integer NOT NULL
);


ALTER TABLE public.detalle_historia_clinica OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16650)
-- Name: detalle_historia_clinica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_historia_clinica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_historia_clinica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16599)
-- Name: historia_clinica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historia_clinica (
    id integer NOT NULL,
    fecha_creacion integer,
    mascota_id integer NOT NULL
);


ALTER TABLE public.historia_clinica OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16597)
-- Name: historia_clinica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historia_clinica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historia_clinica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 16606)
-- Name: mascota; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mascota (
    id integer NOT NULL,
    nombre character varying(255),
    raza character varying(255),
    sexo character varying(255),
    usuario_id integer NOT NULL
);


ALTER TABLE public.mascota OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16604)
-- Name: mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mascota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16616)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    apellido character varying(255),
    documento_identificacion integer,
    estado character varying(255),
    nombre character varying(255),
    sexo integer,
    tipo_documento character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16614)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2862 (class 0 OID 16579)
-- Dependencies: 203
-- Data for Name: colaborador; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.colaborador (id, apellido, cargo, documento_identificacion, especialidad, nombre, tipo_documento) FROM stdin;
1	Gomez	Veterinario	87654321	Canino	Ana	CC
2	Perez	Ingeniero	12345678	Civil	Juan	DNI
\.


--
-- TOC entry 2870 (class 0 OID 16652)
-- Dependencies: 211
-- Data for Name: detalle_historia_clinica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_historia_clinica (id, alimentacion, fecha_hora, frecuencia_cardiaca, frecuencia_respiratoria, habitad, observacion, peso, temperatura, colaborador_id, historia_clinica_id) FROM stdin;
18	Comida	2024-06-08 15:30:10.843	85.00	20.00	finca	Ninguna	5.20	36.5	1	26
17	Croquetas y agua	2023-06-07 09:00:00	90.00	28.00	Casa	Ninguna	5.30	37.0	2	26
\.


--
-- TOC entry 2864 (class 0 OID 16599)
-- Dependencies: 205
-- Data for Name: historia_clinica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historia_clinica (id, fecha_creacion, mascota_id) FROM stdin;
26	20240627	2
\.


--
-- TOC entry 2866 (class 0 OID 16606)
-- Dependencies: 207
-- Data for Name: mascota; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mascota (id, nombre, raza, sexo, usuario_id) FROM stdin;
1	Fido	Labrador	M	1
2	Fido	Labrador Retriever	Macho	1
3	Fido	Labrador Retriever	Macho	1
8	Fido	Labrador Retriever	Hembra	1
11	Lucas	Criollo	Macho	1
9	Max	Criollo	Macho	1
\.


--
-- TOC entry 2868 (class 0 OID 16616)
-- Dependencies: 209
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, apellido, documento_identificacion, estado, nombre, sexo, tipo_documento) FROM stdin;
1	Perez	12345678	Activo	Juan	1	CC
\.


--
-- TOC entry 2877 (class 0 OID 0)
-- Dependencies: 202
-- Name: colaborador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.colaborador_id_seq', 2, true);


--
-- TOC entry 2878 (class 0 OID 0)
-- Dependencies: 210
-- Name: detalle_historia_clinica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_historia_clinica_id_seq', 18, true);


--
-- TOC entry 2879 (class 0 OID 0)
-- Dependencies: 204
-- Name: historia_clinica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historia_clinica_id_seq', 26, true);


--
-- TOC entry 2880 (class 0 OID 0)
-- Dependencies: 206
-- Name: mascota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mascota_id_seq', 11, true);


--
-- TOC entry 2881 (class 0 OID 0)
-- Dependencies: 208
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, true);


--
-- TOC entry 2716 (class 2606 OID 16586)
-- Name: colaborador colaborador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colaborador
    ADD CONSTRAINT colaborador_pkey PRIMARY KEY (id);


--
-- TOC entry 2728 (class 2606 OID 16659)
-- Name: detalle_historia_clinica detalle_historia_clinica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_historia_clinica
    ADD CONSTRAINT detalle_historia_clinica_pkey PRIMARY KEY (id);


--
-- TOC entry 2718 (class 2606 OID 16603)
-- Name: historia_clinica historia_clinica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historia_clinica
    ADD CONSTRAINT historia_clinica_pkey PRIMARY KEY (id);


--
-- TOC entry 2722 (class 2606 OID 16613)
-- Name: mascota mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT mascota_pkey PRIMARY KEY (id);


--
-- TOC entry 2724 (class 2606 OID 16629)
-- Name: usuario uk3ocvbeh126ooi1bvcfc7yydaw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk3ocvbeh126ooi1bvcfc7yydaw UNIQUE (documento_identificacion);


--
-- TOC entry 2720 (class 2606 OID 16627)
-- Name: historia_clinica ukifwmmf2s5ea31ep30nagbqi56; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historia_clinica
    ADD CONSTRAINT ukifwmmf2s5ea31ep30nagbqi56 UNIQUE (mascota_id);


--
-- TOC entry 2730 (class 2606 OID 16661)
-- Name: detalle_historia_clinica uksi2ad17jf4j1ak0aralyvwwrq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_historia_clinica
    ADD CONSTRAINT uksi2ad17jf4j1ak0aralyvwwrq UNIQUE (colaborador_id);


--
-- TOC entry 2726 (class 2606 OID 16623)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 2731 (class 2606 OID 16640)
-- Name: historia_clinica fk8qtajjx6p7pi6ltqn1ngm54sv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historia_clinica
    ADD CONSTRAINT fk8qtajjx6p7pi6ltqn1ngm54sv FOREIGN KEY (mascota_id) REFERENCES public.mascota(id);


--
-- TOC entry 2733 (class 2606 OID 16662)
-- Name: detalle_historia_clinica fkmx53cne878vbngvx4cx44q77m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_historia_clinica
    ADD CONSTRAINT fkmx53cne878vbngvx4cx44q77m FOREIGN KEY (colaborador_id) REFERENCES public.colaborador(id);


--
-- TOC entry 2734 (class 2606 OID 16667)
-- Name: detalle_historia_clinica fkn9o6pjrd64f0qha1o4qp1x9y7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_historia_clinica
    ADD CONSTRAINT fkn9o6pjrd64f0qha1o4qp1x9y7 FOREIGN KEY (historia_clinica_id) REFERENCES public.historia_clinica(id);


--
-- TOC entry 2732 (class 2606 OID 16645)
-- Name: mascota fko76id5o9j6vtffestw0tkrrtt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT fko76id5o9j6vtffestw0tkrrtt FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 2876 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2024-06-08 17:59:42

--
-- PostgreSQL database dump complete
--

